### ISSUE TITLE
Preview in gedit itself

### ISSUE THREAD

**Issue by bilderbuchi** [nemec/gedit-markdown-preview#1]
Hi!

It would be nice to have the md preview in gedit itself, in the bottom or side bar, like this plugin does:
http://live.gnome.org/Gedit/MarkdownSupport
There would be no need for browser and web server then. Sadly, that plugin doesn't seem to work any more with the transition to gnome3.

Have you already thought about that? What do you say?

**Comment by nemec** [comment]
Ah, so that plugin uses the bottom panel to display the preview. Not a bad idea. I'd thought about adding the preview in Gedit itself but was looking for a more "split screen" way to do it (since I keep the side and bottom panels small). 

It looks like he has a Gnome3 version up on his actual site: http://jpfleury.indefero.net/p/gedit-markdown/source/tree/master/plugins/gedit3

I'll definitely check out alternatives to the webserver, though.

**Comment by bilderbuchi** [comment]
Huh, somehow missed that version. It works, nice. :-)
Split screen also sounds nice, although for me the bottom panel does effectively that, I don't use it for much else.

**Comment by bilderbuchi** [comment]
Closing this old issue.
